#|
 This file is a part of zippy
 (c) 2020 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.zippy)

(defun alist-vector (alist)
  (let* ((max (loop for cons in alist maximize (car cons)))
         (vec (make-array (1+ max) :initial-element :unknown)))
    (loop for (i . e) in alist
          do (setf (svref vec i) e))
    vec))

(defun alist-table (alist)
  (let ((table (make-hash-table)))
    (loop for (i . e) in alist
          do (setf (gethash i table) e))
    table))

(defparameter *file-attribute-compatibility-map*
  (alist-vector '((0 . :ms-dos)
                  (1 . :amiga)
                  (2 . :open-vms)
                  (3 . :unix)
                  (4 . :vm/cms)
                  (5 . :atari-st)
                  (6 . :os/2)
                  (7 . :macintosh)
                  (8 . :z-system)
                  (9 . :cp/m)
                  (10 . :ntfs)
                  (11 . :mvs)
                  (12 . :vse)
                  (13 . :acorn-risc)
                  (14 . :vfat)
                  (15 . :alternate-mvs)
                  (16 . :beos)
                  (17 . :tandem)
                  (18 . :os/400)
                  (19 . :darwin))))

(defparameter *compression-method-map*
  (alist-vector '((0 . NIL)
                  (1 . :shrink)
                  (2 . :reduce-1)
                  (3 . :reduce-2)
                  (4 . :reduce-3)
                  (5 . :reduce-4)
                  (6 . :implode)
                  (7 . :tokenizing)
                  (8 . :deflate)
                  (9 . :deflate64)
                  (10 . :pkware-implode)
                  (11 . :reserved)
                  (12 . :bzip2)
                  (13 . :reserved)
                  (14 . :lzma)
                  (15 . :reserved)
                  (16 . :cmpsc)
                  (17 . :reserved)
                  (18 . :terse)
                  (19 . :lz77)
                  (20 . :zstd)
                  (96 . :jpeg)
                  (97 . :wavpack)
                  (98 . :ppmd)
                  (99 . :ae-x))))

(defparameter *encryption-method-map*
  (alist-table '((#x6601 . :des)
                 (#x6602 . :rc2)
                 (#x6603 . :3des-168)
                 (#x6609 . :3des-112)
                 (#x660e . :aes-128) 
                 (#x660f . :aes-192) 
                 (#x6610 . :aes-256) 
                 (#x6702 . :rc2)
                 (#x6720 . :blowfish)
                 (#x6721 . :twofish)
                 (#x6801 . :rc4)
                 (#xffff . :unknown))))
