#|
 This file is a part of zippy
 (c) 2020 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.zippy)

(defvar *file-attribute-compatibility-map*
  (alexandria:alist-hash-table '((0 . :ms-dos)
                                 (1 . :amiga)
                                 (2 . :open-vms)
                                 (3 . :unix)
                                 (4 . :vm/cms)
                                 (5 . :atari-st)
                                 (6 . :os/2)
                                 (7 . :macintosh)
                                 (8 :z-system)
                                 (9 :cp/m)
                                 (10 :ntfs)
                                 (11 :mvs)
                                 (12 :vse)
                                 (13 :acorn-risc)
                                 (14 :vfat)
                                 (15 :alternate-mvs)
                                 (16 :beos)
                                 (17 :tandem)
                                 (18 :os/400)
                                 (19 :darwin))))

(defvar *compression-method-map*
  (alexandria:alist-hash-table '((0 . NIL)
                                 (1 . :shrink)
                                 (2 . :reduce-1)
                                 (3 . :reduce-2)
                                 (4 . :reduce-3)
                                 (5 . :reduce-4)
                                 (6 . :implode)
                                 (7 . :tokenizing)
                                 (8 . :deflate)
                                 (9 . :deflate64)
                                 (10 . :pkware-implode)
                                 (11 . :reserved)
                                 (12 . :bzip2)
                                 (13 . :reserved)
                                 (14 . :lzma)
                                 (15 . :reserved)
                                 (16 . :cmpsc)
                                 (17 . :reserved)
                                 (18 . :terse)
                                 (19 . :lz77)
                                 (20 . :zstd)
                                 (96 . :jpeg)
                                 (97 . :wavpack)
                                 (98 . :ppmd)
                                 (99 . :ae-x))))
